-- 文章表
DROP TABLE IF EXISTS `article`;
CREATE TABLE `article` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '文章ID',
  `article_key` VARCHAR(50) NOT NULL COMMENT '文章唯一标识',
  `title` VARCHAR(255) NOT NULL COMMENT '文章标题',
  `slug` VARCHAR(255) DEFAULT NULL COMMENT '别名',
  `content` LONGTEXT NOT NULL COMMENT '文章内容',
  `excerpt` TEXT DEFAULT NULL COMMENT '摘要',
  `cover` VARCHAR(512) DEFAULT NULL COMMENT '文章封面',
  `author_id` BIGINT DEFAULT NULL COMMENT '作者ID（与账号表关联）',
  `category_id` BIGINT DEFAULT NULL COMMENT '分类ID',
  `type` VARCHAR(20) NOT NULL DEFAULT '1' COMMENT '文章类型（1原创2转载3翻译4引用）',
  `original_author` VARCHAR(30) DEFAULT NULL COMMENT '原文作者',
  `original_title` VARCHAR(50) DEFAULT NULL COMMENT '原文标题',
  `original_url` VARCHAR(512) DEFAULT NULL COMMENT '原文链接',
  `note` VARCHAR(300) DEFAULT NULL COMMENT '文章备注信息',
  `status` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '文章状态（0-草稿，1-已发布）',
  `is_top` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '文章是否置顶显示',
  `view_count` INT NOT NULL DEFAULT '0' COMMENT '浏览量',
  `like_count` INT NOT NULL DEFAULT '0' COMMENT '点赞数',
  `comment_count` INT NOT NULL DEFAULT '0' COMMENT '评论数',
  `published_at` DATETIME DEFAULT NULL COMMENT '发布时间',
  `deleted` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '是否已删除',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_article_key` (`article_key`),
  UNIQUE KEY `uk_slug` (`slug`),
  KEY `idx_author_id` (`author_id`),
  KEY `idx_category_id` (`category_id`),
  KEY `idx_status` (`status`),
  KEY `idx_is_top` (`is_top`),
  KEY `idx_published_at` (`published_at`),
  KEY `idx_deleted` (`deleted`),
  CONSTRAINT `fk_article_author_id` FOREIGN KEY (`author_id`) REFERENCES `user` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_article_category_id` FOREIGN KEY (`category_id`) REFERENCES `category` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='博客文章表';

