-- 说说表
DROP TABLE IF EXISTS `talk`;
CREATE TABLE `talk` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '说说ID',
  `talk_key` VARCHAR(50) NOT NULL COMMENT '说说唯一标识',
  `content` LONGTEXT NOT NULL COMMENT '说说内容',
  `images` TEXT DEFAULT NULL COMMENT '图片（JSON数组）',
  `author_id` BIGINT DEFAULT NULL COMMENT '发表人账号ID',
  `like_count` INT NOT NULL DEFAULT '0' COMMENT '点赞数',
  `comment_count` INT NOT NULL DEFAULT '0' COMMENT '评论数',
  `status` VARCHAR(20) NOT NULL DEFAULT '1' COMMENT '状态（1显示2私密）',
  `is_top` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '置顶（1置顶0不置顶）',
  `ip` VARCHAR(50) DEFAULT NULL COMMENT 'IP地址',
  `ip_address` VARCHAR(255) DEFAULT NULL COMMENT 'IP地址信息',
  `country` VARCHAR(50) DEFAULT NULL COMMENT '国家',
  `province` VARCHAR(50) DEFAULT NULL COMMENT '省份',
  `city` VARCHAR(50) DEFAULT NULL COMMENT '城市',
  `latitude` DECIMAL(10,7) DEFAULT NULL COMMENT '纬度',
  `longitude` DECIMAL(10,7) DEFAULT NULL COMMENT '经度',
  `location_detail` VARCHAR(255) DEFAULT NULL COMMENT '详细地址',
  `device_info` VARCHAR(255) DEFAULT NULL COMMENT '设备信息',
  `point` POINT DEFAULT NULL COMMENT '坐标点',
  `location` VARCHAR(100) DEFAULT NULL COMMENT '位置',
  `deleted` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '是否已删除',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_talk_key` (`talk_key`),
  KEY `idx_author_id` (`author_id`),
  KEY `idx_status` (`status`),
  KEY `idx_is_top` (`is_top`),
  KEY `idx_deleted` (`deleted`),
  CONSTRAINT `fk_talk_author_id` FOREIGN KEY (`author_id`) REFERENCES `user` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='说说表';

