-- 评论表
DROP TABLE IF EXISTS `comment`;
CREATE TABLE `comment` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '评论ID',
  `comment_key` VARCHAR(50) DEFAULT NULL COMMENT '评论唯一标识',
  `content` TEXT NOT NULL COMMENT '评论内容',
  `images` VARCHAR(2048) DEFAULT '[]' COMMENT '图片（JSON数组）',
  `post_id` BIGINT DEFAULT NULL COMMENT '文章ID',
  `moment_id` BIGINT DEFAULT NULL COMMENT '说说ID',
  `user_id` BIGINT DEFAULT NULL COMMENT '用户ID',
  `parent_id` BIGINT NOT NULL DEFAULT '0' COMMENT '回复的评论ID',
  `root_id` BIGINT NOT NULL DEFAULT '0' COMMENT '根评论ID',
  `type` VARCHAR(20) NOT NULL COMMENT '评论类型(1登录评论2游客评论3匿名评论)',
  `nickname` VARCHAR(30) DEFAULT NULL COMMENT '游客别名',
  `email` VARCHAR(128) DEFAULT NULL COMMENT '游客邮箱',
  `qq` VARCHAR(15) DEFAULT NULL COMMENT '游客QQ号',
  `status` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '审核状态（0-待审核，1-已通过）',
  `is_visible` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '是否隐藏评论',
  `ip` VARCHAR(50) NOT NULL COMMENT 'IP地址',
  `ip_address` VARCHAR(255) NOT NULL COMMENT 'IP地址信息',
  `country` VARCHAR(50) DEFAULT NULL COMMENT '国家',
  `province` VARCHAR(50) DEFAULT NULL COMMENT '省份',
  `city` VARCHAR(50) DEFAULT NULL COMMENT '城市',
  `latitude` DECIMAL(10,7) DEFAULT NULL COMMENT '纬度',
  `longitude` DECIMAL(10,7) DEFAULT NULL COMMENT '经度',
  `location_detail` VARCHAR(255) DEFAULT NULL COMMENT '详细地址',
  `device_info` VARCHAR(255) DEFAULT NULL COMMENT '设备信息',
  `device` VARCHAR(50) NOT NULL DEFAULT '未知设备' COMMENT '使用设备',
  `browser` VARCHAR(50) NOT NULL DEFAULT '未知浏览器' COMMENT '使用的浏览器',
  `point` POINT DEFAULT NULL COMMENT '坐标点',
  `location` VARCHAR(100) DEFAULT NULL COMMENT '位置',
  `deleted` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '是否已删除',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_comment_key` (`comment_key`),
  KEY `idx_post_id` (`post_id`),
  KEY `idx_moment_id` (`moment_id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_parent_id` (`parent_id`),
  KEY `idx_root_id` (`root_id`),
  KEY `idx_status` (`status`),
  KEY `idx_deleted` (`deleted`),
  CONSTRAINT `fk_comment_post_id` FOREIGN KEY (`post_id`) REFERENCES `article` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_comment_moment_id` FOREIGN KEY (`moment_id`) REFERENCES `talk` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_comment_user_id` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='评论信息表';

