-- 访客表
DROP TABLE IF EXISTS `visitor`;
CREATE TABLE `visitor` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '访客ID',
  `visitor_uuid` VARCHAR(64) NOT NULL COMMENT '访客唯一标识',
  `ip` VARCHAR(50) NOT NULL COMMENT 'IP地址',
  `ip_address` VARCHAR(255) DEFAULT NULL COMMENT 'IP地址信息',
  `country` VARCHAR(50) DEFAULT NULL COMMENT '国家',
  `province` VARCHAR(50) DEFAULT NULL COMMENT '省份',
  `city` VARCHAR(50) DEFAULT NULL COMMENT '城市',
  `latitude` DECIMAL(10,7) DEFAULT NULL COMMENT '纬度',
  `longitude` DECIMAL(10,7) DEFAULT NULL COMMENT '经度',
  `location_detail` VARCHAR(255) DEFAULT NULL COMMENT '详细地址',
  `device_info` VARCHAR(255) DEFAULT NULL COMMENT '设备信息',
  `browser` VARCHAR(50) DEFAULT NULL COMMENT '浏览器',
  `os` VARCHAR(50) DEFAULT NULL COMMENT '操作系统',
  `referer` VARCHAR(255) DEFAULT NULL COMMENT '来源',
  `visit_count` INT NOT NULL DEFAULT '1' COMMENT '访问次数',
  `last_visit_time` DATETIME NOT NULL COMMENT '最后访问时间',
  `first_visit_time` DATETIME NOT NULL COMMENT '首次访问时间',
  `status` VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT '访客状态',
  `district` VARCHAR(100) DEFAULT NULL COMMENT '区/县',
  `isp` VARCHAR(100) DEFAULT NULL COMMENT 'ISP运营商',
  `timezone` VARCHAR(50) DEFAULT NULL COMMENT '时区',
  `device_type` VARCHAR(50) DEFAULT NULL COMMENT '设备类型',
  `device_brand` VARCHAR(50) DEFAULT NULL COMMENT '设备品牌',
  `device_model` VARCHAR(100) DEFAULT NULL COMMENT '设备型号',
  `os_name` VARCHAR(50) DEFAULT NULL COMMENT '操作系统名称',
  `os_version` VARCHAR(50) DEFAULT NULL COMMENT '操作系统版本',
  `browser_name` VARCHAR(50) DEFAULT NULL COMMENT '浏览器名称',
  `browser_version` VARCHAR(50) DEFAULT NULL COMMENT '浏览器版本',
  `traffic_source` VARCHAR(50) DEFAULT NULL COMMENT '流量来源分类',
  `referer_url` VARCHAR(500) DEFAULT NULL COMMENT '来源页面URL',
  `search_engine` VARCHAR(50) DEFAULT NULL COMMENT '搜索引擎名称',
  `search_keywords` VARCHAR(200) DEFAULT NULL COMMENT '搜索关键词',
  `utm_source` VARCHAR(100) DEFAULT NULL COMMENT 'UTM来源参数',
  `utm_medium` VARCHAR(100) DEFAULT NULL COMMENT 'UTM媒介参数',
  `utm_campaign` VARCHAR(100) DEFAULT NULL COMMENT 'UTM活动参数',
  `deleted` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '是否已删除',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_visitor_uuid` (`visitor_uuid`),
  UNIQUE KEY `uk_ip` (`ip`),
  KEY `idx_last_visit_time` (`last_visit_time`),
  KEY `idx_country` (`country`),
  KEY `idx_city` (`city`),
  KEY `idx_status` (`status`),
  KEY `idx_deleted` (`deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='访客记录表';

