-- 操作日志表
DROP TABLE IF EXISTS `log_operation`;
CREATE TABLE `log_operation` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '操作日志ID',
  `user_id` BIGINT DEFAULT NULL COMMENT '操作用户ID',
  `username` VARCHAR(50) DEFAULT NULL COMMENT '用户名',
  `operation` VARCHAR(100) NOT NULL COMMENT '操作',
  `method` VARCHAR(10) DEFAULT NULL COMMENT '请求方法',
  `path` VARCHAR(255) DEFAULT NULL COMMENT '请求路径',
  `params` TEXT DEFAULT NULL COMMENT '请求参数',
  `result` TEXT DEFAULT NULL COMMENT '返回结果',
  `ip` VARCHAR(50) DEFAULT NULL COMMENT 'IP地址',
  `ip_address` VARCHAR(255) DEFAULT NULL COMMENT 'IP地址信息',
  `duration` BIGINT DEFAULT NULL COMMENT '耗时（毫秒）',
  `status` TINYINT(1) NOT NULL DEFAULT '1' COMMENT '状态（0-失败，1-成功）',
  `error_msg` TEXT DEFAULT NULL COMMENT '错误信息',
  `version` VARCHAR(128) DEFAULT NULL COMMENT '项目版本',
  `module` VARCHAR(20) DEFAULT NULL COMMENT '操作模块',
  `calling_method` VARCHAR(255) DEFAULT NULL COMMENT '调用的方法',
  `type` VARCHAR(20) DEFAULT NULL COMMENT '操作类型（新增、修改...）',
  `description` VARCHAR(100) DEFAULT NULL COMMENT '操作描述信息',
  `request_url` VARCHAR(255) DEFAULT NULL COMMENT '请求地址',
  `request_method` VARCHAR(10) DEFAULT NULL COMMENT '请求方法',
  `request_param` LONGTEXT DEFAULT NULL COMMENT '请求参数',
  `response_data` LONGTEXT DEFAULT NULL COMMENT '响应参数',
  `elapsed_time` BIGINT DEFAULT NULL COMMENT '操作执行耗时毫秒数',
  `device` VARCHAR(50) DEFAULT NULL COMMENT '设备',
  `browser` VARCHAR(50) DEFAULT NULL COMMENT '浏览器',
  `ip_source` VARCHAR(150) DEFAULT NULL COMMENT 'ip归属地',
  `deleted` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '是否被删除',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_create_time` (`create_time`),
  KEY `idx_status` (`status`),
  KEY `idx_operation` (`operation`),
  KEY `idx_deleted` (`deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='操作日志表';

